const TOOLS = {
  RECTANGLE: "RECTANGLE",
  CIRCLE: "CIRCLE",
  LINE: "LINE",
  PEN: "PEN",
  ARROW: "ARROW",
  ERASER: "ERASER",
  TEXT: "TEXT",
  UNDO: "UNDO",
  REDO: "REDO",
};

const BOARD_ACTION_TYPE = {
  DRAWING: "DRAWING",
  ERASING: "ERASING",
  WRITING: "WRITING",
  NONE: "NONE",
};

const BOARD_ACTIONS = {
  CHANGE_TOOL: "CHANGE_TOOL",
  DRAW_DOWN: "DRAW_DOWN",
  DRAW_MOVE: "DRAW_MOVE",
  DRAW_UP: "DRAW_UP",
  ERASE: "ERASE",
  CHANGE_ACTION_TYPE: "CHANGE_ACTION_TYPE",
  CHANGE_TEXT: "CHANGE_TEXT",
  HISTORY_PUSH: "HISTORY_PUSH",
  UNDO: "UNDO",
  REDO: "REDO",
  DOWNLOAD: "DOWNLOAD",
  SET_PROFILE: "SET_PROFILE",
  SET_LOGIN_STATUS: "SET_LOGIN_STATUS",
  LOGOUT: "LOGOUT",
  SET_CANVASES: "SET_CANVASES",
  SET_ELEMENTS: "SET_ELEMENTS",
  CHANGE_CANVAS_ID: "CHANGE_CANVAS_ID",
};

const ARROW_LENGTH = 20;

const COLORS = {
  NONE: "",
  BLACK: "#000000",
  RED: "#ff0000",
  GREEN: "#00ff00",
  BLUE: "#0000ff",
  ORANGE: "#ffa500",
  YELLOW: "#ffff00",
  WHITE: "#ffffff",
};
const TOOLBOX_ACTIONS = {
  CHANGE_STROKE: "CHANGE_STROKE",
  CHANGE_FILL: "CHANGE_FILL",
  CHANGE_SIZE: "CHANGE_SIZE",
};

const FILL_ITEMS = ["RECTANGLE", "CIRCLE"];
const ELEMENT_ERASE_THRESHOLD = 0.1;
export {
  TOOLS,
  BOARD_ACTIONS,
  ARROW_LENGTH,
  COLORS,
  TOOLBOX_ACTIONS,
  FILL_ITEMS,
  BOARD_ACTION_TYPE,
  ELEMENT_ERASE_THRESHOLD,
};
