const TOOLS = {
  RECTANGLE: "RECTANGLE",
  CIRCLE: "CIRCLE",
  LINE: "LINE",
  PEN: "PEN",
  ARROW: "ARROW",
};

const BOARD_ACTIONS = {
  CHANGE_TOOL: "CHANGE_TOOL",
  DRAW_DOWN: "DRAW_DOWN",
  DRAW_MOVE: "DRAW_MOVE",
  DRAW_UP: "DRAW_UP",
};

const ARROW_LENGTH = 20;

const COLORS = {
  NONE: "",
  BLACK: "#000000",
  RED: "#ff0000",
  GREEN: "#00ff00",
  BLUE: "#0000ff",
  ORANGE: "#ffa500",
  YELLOW: "#ffff00",
  WHITE: "#ffffff",
};
const TOOLBOX_ACTIONS = {
  CHANGE_STROKE: "CHANGE_STROKE",
  CHANGE_FILL: "CHANGE_FILL",
  CHANGE_SIZE: "CHANGE_SIZE",
};

const FILL_ITEMS = ["RECTANGLE", "CIRCLE"];

export {
  TOOLS,
  BOARD_ACTIONS,
  ARROW_LENGTH,
  COLORS,
  TOOLBOX_ACTIONS,
  FILL_ITEMS,
};
